backend:
  name: git-gateway
  branch: master
site_url: https://www.pickeringaviation.com
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - label: Site Data
    name: meta
    delete: false
    files: 
      - label: Site Meta Data
        name: data
        file: meta/data.md
        fields:
          - { label: Site Title, name: title }
          - { label: Site Description, name: description }
          - { label: Logo (For Navigation), name: logo, widget: image }
          - { label: Logo Alternative Text (For Navigation), name: alt }
      - label: Other Site Data
        name: other
        identifier_field: contact
        file: meta/other.md
        fields: 
          - { label: General Contact Link, name: contact }
